Sprint 2/step 1
leopard-work/react-burger pull request #3
Opened 2022-09-13 18:40 UTC by leopard-work

2022-09-13 20:23 UTC, randomroot commented
1

2022-09-13 20:59 UTC, randomroot requested changes
Доброго времени суток!

На данном этапе вы успешно реализовали работу с контекстом и обеспечили удобный способ по передаче данных в дочерние компоненты. 
Однако, для успешной сдачи работы вам необходимо исправить моменты, отмеченные в ревью, особое внимание обратите на:
1) Правильность работы с контекстом в дочерних компонентах;
2) Работу с модальным окном результатов заказа;
3) Хранение данных в хуке useState

Также, в рамках ревью были обозначены моменты, которые помогут вам обеспечить высокое качество вашего кода и упростить дальнейшее развитие проекта. Также отмечу, что хорошей практикой является вынесение слоя работы с API в отдельную папку/файл (например utils/api.js), где вы сможете исключить дублирования URL сервера и сделать ваши методы более универсальными (т.к. часть функционала по обработке результата схожа/одинакова).

2022-09-13 20:59 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
>              <Modal isOpen={state.modalOpen} close={modalChange}>
🟡 **Можно улучшить:**

Несмотря на то, что данный код не изменялся в рамках данного MR стоит отметить, что хорошей практикой является рендеринг компонента модального окна по условию, вместо передачи значения `open` через пропс. С архитектурной точки зрения, модальное окно ответственно за отображения контента, а также вызов функции по его закрытию, в то время как родительский компонент решает, когда окно должно быть открыто или закрыто. Плюс, если мы не отображаем компонент, то и React-у легче, ведь ему не надо добавлять еще одного потомка в своё дерево, когда он не требуется :)

2022-09-13 20:59 UTC, randomroot commented on src/components/order-details/order-details.jsx
> +    useEffect(() => {
🔴 **Нужно исправить:**

С точки зрения архитектуры в проекте и общепринятых практик, следует придерживаться следующего принципа: за формирование и создание заказа отвечает компонент `BurgerConstructor`, и если запрос проходит успешно, то отображается компонент `OrderDetails` с результатами выполненного запроса, Таким образом, упростится логика в `OrderDetails` и не будет необходимости в использовании `useContext`

2022-09-13 20:59 UTC, randomroot commented on src/components/order-details/order-details.jsx
> +                <div className={styles.checkout + " pt-30 pb-30"}>
🟡 **Можно улучшить:**

В случае слияния строк можно использовать "шаблонные строки", что улучшит читаемость вашего кода и слегка улучшит его производительность.
(см. https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Template_literals)

2022-09-13 20:59 UTC, randomroot commented on src/components/app/app.jsx
> +    const [orderItems, setOrderItems] = useState({
🟡 **Можно улучшить:**

В большинстве случаев использование хука `useState` следует принципам одно значение - один хук, что позволяет нам независимо обновлять переменные, не создавая каждый раз новый объект. В данном примере, значение orderInfo не зависит от items/totalPrice и при его обновлении будет задействоваться дополнительная память, которую можно избежать, если вынести его в отдельную переменную с хуком.
(см. https://ru.reactjs.org/docs/hooks-faq.html#should-i-use-one-or-many-state-variables)

2022-09-13 20:59 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +        items: orderItems.items.map((item, i) => item.type !== 'bun' ? <ConsructorItem key={item._id} item={item}/> : ''),
🔴 **Нужно исправить:**

1) Не следует хранить JSX элементы в рамках `useState`, в переменных состояния должны хранится именно данные, на основе которых и строится интерфейс. При каждом изменении состояния React сравнивает значения и в случае компонентов - это будет довольно непростой задачей, по сравнению с простым массивов объектов со значениями. Ранее в документации для классовых компонентов этот момент был описан напрямую, но к сожалению, для функциональных этот момент был опущен, хотя и остается актуальным по сей день (см. https://stackoverflow.com/a/47875226)

2) В названии компонента `ConsructorItem` допущена опечатка

🟡 **Можно улучшить:**

Для хранения данных, которые вычисляются на основе пропсов или других данных и не изменяются или изменяются в зависимости от какой-то переменной можно использовать хук `useMemo`, который создан как раз с целью мемоизации значений (см. https://ru.reactjs.org/docs/hooks-reference.html#usememo)

2022-09-13 20:59 UTC, randomroot commented on src/index.tsx
> +  /*</React.StrictMode>*/
🟡 **Можно улучшить:**

Не рекомендуется отключать `StrictMode` (см. https://ru.reactjs.org/docs/strict-mode.html), так как он позволяет разработчику обратить внимание на проблемы, связанные с устареванием той или иной технологии из прошлых версий React-а. Однако, если вы сталкиваетесь с проблемой двойного рендеринга одного из ваших компонентов как раз из-за наличия данного режима, то отключение считается целесообразным выходом из положения.

2022-09-13 20:59 UTC, randomroot commented on src/components/app/app.jsx
>                      loading: false,
🟡 **Можно улучшить:**

1) Изменение состояние `loading` целесообразно вынести в блок `finally`, чтобы значение поменялось даже в случае ошибки `fetch`;
2) В данный момент это состояние не используется в рамках интерфейса, рекомендую в дальнейшем добавить лоадер на список ингредиентов, чтобы показать пользователю визуально, что идёт запрос на сервер (ведь он может занимать и некоторое время, в зависимости от загруженности сервера и качества интернет-соединения)

2022-09-14 16:00 UTC, randomroot approved these changes
Отличная работа, требования к заданию выполнены, отмечу, что код лаконичен и удачно разделен на компоненты, нужный функционал был успешно реализован, в том числе учтены большинство пожеланий к улучшению, за счет чего вам удалось улучшить качество кода и архитектуру в проекте 👍 

Из пожеланий на будущее: хотел бы обратить ваше внимание на функциональную составляющую компонента `Tabs`: на данный момент взаимодействие с ними не выполняет команд, в будущем рекомендуется добавить переход к нужной категории по нажатию на них, т.к. это может засчитать как ошибка при будущих проверках.

Успехов в обучении 🐈

2022-09-14 17:28 UTC, leopard-work commented on src/components/burger-constructor/burger-constructor.jsx
> +    const bun = orderItems.filter(item => item.type === 'bun');
Спасибо за проверку и полезные комментарии!

2022-09-16 14:33 UTC, merged